---
title: "Luftvejsdata Visualisering"
author: "Niels Dalum Hansen"
date: "5 apr 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(TSA)
source("ReadData.R")
```

## Influenza data
```{r, include=FALSE}
influenza_data = load_influenza_data()
```

We have influenza data from 2010 to 2018

### Plots of influenza data

```{r influenza plot, echo=FALSE, warning=FALSE}
influenza_data_weekly <- influenza_data$weekly_data
ggplot(data=influenza_data_weekly, aes(weekdate, y=value, color=variable)) +
  geom_line(aes(y=a, col="a")) +
  geom_line(aes(y=b, col="b")) +
  geom_line(aes(y=c, col="c")) +
  geom_line(aes(y=h1n1, col="h1n1")) +
  geom_line(aes(y=h3n2, col="h3n2")) +
  labs(title="Plot of influenza data", x="Date", y="Number of weekly positive tests")
```


```{r, echo=FALSE}
influenza_person <- influenza_data$person_data
hist(influenza_person$alder, xlab="Alder", main="Histogram af alder ved prøvetagning")
```


```{r, echo=FALSE, warning=FALSE}
p = periodogram(influenza_data_weekly$a, plot=FALSE)
dd = data.frame(freq=1/p$freq, spec=p$spec)
#order = dd[order(-dd$spec),]
ggplot(data=dd) + geom_line(aes(freq, spec)) + geom_point(aes(freq, spec)) + xlim(0, 104) + labs(x="Weeks", y="", title="Fourier transform of influenza a", caption="Frequency scaled to weeks")
```

```{r, echo=FALSE, warning=FALSE}
p = periodogram(influenza_data_weekly$b, plot=FALSE)
dd = data.frame(freq=1/p$freq, spec=p$spec)
#order = dd[order(-dd$spec),]
ggplot(data=dd) + geom_line(aes(freq, spec)) + geom_point(aes(freq, spec)) + xlim(0, 104) + labs(x="Weeks", y="", title="Fourier transform of influenza b", caption="Frequency scaled to weeks")
```

```{r, echo=FALSE, warning=FALSE}
p = periodogram(influenza_data_weekly$c, plot=FALSE)
dd = data.frame(freq=1/p$freq, spec=p$spec)
#order = dd[order(-dd$spec),]
ggplot(data=dd) + geom_line(aes(freq, spec)) + geom_point(aes(freq, spec)) + xlim(0, 104) + labs(x="Weeks", y="", title="Fourier transform of influenza c", caption="Frequency scaled to weeks")
```

```{r, echo=FALSE, include=FALSE}
p = periodogram(influenza_data_weekly$h1n1, plot=FALSE)
dd = data.frame(freq=1/p$freq, spec=p$spec)
#order = dd[order(-dd$spec),]
ggplot(data=dd) + geom_line(aes(freq, spec)) + geom_point(aes(freq, spec)) + xlim(0, 104) + labs(x="Weeks", y="", title="Fourier transform of influenza h1n1", caption="Frequency scaled to weeks")
```

```{r, echo=FALSE, warning=FALSE}
p = periodogram(influenza_data_weekly$h3n2, plot=FALSE)
dd = data.frame(freq=1/p$freq, spec=p$spec)
#order = dd[order(-dd$spec),]
ggplot(data=dd) + geom_line(aes(freq, spec)) + geom_point(aes(freq, spec)) + xlim(0, 104) + labs(x="Weeks", y="", title="Fourier transform of influenza h3n2", caption="Frequency scaled to weeks")
```

## Mycoplasma data

```{r, include=FALSE}
mycoplasma_data = load_mycoplasma_data()
```


### Plots of Mycoplasma data

```{r, echo=FALSE, warning=FALSE}
mycoplasma_data_weekly <- mycoplasma_data$weekly_data
ggplot(data=mycoplasma_data_weekly, aes(weekdate, y=value, color=variable)) +
  geom_line(aes(y=mycopl, col="Mycoplasma")) +
  labs(title="Plot of Mycoplasma data", x="Date", y="Number of weekly positive tests")
```
```{r echo=FALSE,}
mycoplasma_person <- mycoplasma_data$person_data
hist(mycoplasma_person$age, xlab="Alder", main ="Histogram af alder ved prøvetagning")
```

## Pneumokok data

```{r load data, include=FALSE}
pneumokok_data = load_pneumokok_data()
```


### Plots of pneumokok data

```{r, echo=FALSE, warning=FALSE}
pneumokok_data_weekly <- pneumokok_data$weekly_data
ggplot(data=pneumokok_data_weekly, aes(weekdate, y=value, color=variable)) +
  geom_line(aes(y=count, col="pneumokok")) +
  labs(title="Plot of pneumokok data", x="Date", y="Number of weekly positive tests")
```
```{r echo=FALSE,}
pneumokok_person <- pneumokok_data$person_data
hist(pneumokok_person$Alder, xlab="Alder", main ="Histogram af alder ved prøvetagning")
```

```{r, echo=FALSE, warning=FALSE}
p = periodogram(pneumokok_data_weekly$count, plot=FALSE)
dd = data.frame(freq=1/p$freq, spec=p$spec)
#order = dd[order(-dd$spec),]
ggplot(data=dd) + geom_line(aes(freq, spec)) + geom_point(aes(freq, spec)) + xlim(0, 104) + labs(x="Weeks", y="", title="Fourier transform of pneumokok tests", caption="Frequency scaled to weeks")
```